services:
  - type: web
    name: vertex-rd-geoportal
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
        optional: true
